musican/music/urls.py
from django.urls import path

from . import views

app_name = 'music'

urlpatterns = [
    path('tracks/', views.TrackListView.as_view(), name='track_list'),
    path(
        'tracks/<int:pk>/',
        views.TrackDetailView.as_view(),
        name='track_detail',
    ),
    path(
        'track/create/', views.TrackCreateView.as_view(), name='track_create'
    ),
    path(
        'track/<int:pk>/edit/',
        views.TrackUpdateView.as_view(),
        name='track_edit',
    ),
    path(
        'track/<int:pk>/delete/',
        views.TrackDeleteView.as_view(),
        name='track_delete',
    ),
    path('artists/', views.ArtistListView.as_view(), name='artist_list'),
    path(
        'artist/<int:pk>/',
        views.ArtistDetailView.as_view(),
        name='artist_detail',
    ),
    path(
        'artist/create/',
        views.ArtistCreateView.as_view(),
        name='artist_create',
    ),
    path(
        'artist/<int:pk>/edit/',
        views.ArtistUpdateView.as_view(),
        name='artist_edit',
    ),
    path(
        'artist/<int:pk>/delete/',
        views.ArtistDeleteView.as_view(),
        name='artist_delete',
    ),
    path('groups/', views.GroupListView.as_view(), name='group_list'),
    path(
        'group/<int:pk>/', views.GroupDetailView.as_view(), name='group_detail'
    ),
    path(
        'group/create/', views.GroupCreateView.as_view(), name='group_create'
    ),
    path(
        'group/<int:pk>/edit/',
        views.GroupUpdateView.as_view(),
        name='group_edit',
    ),
    path(
        'group/<int:pk>/delete/',
        views.GroupDeleteView.as_view(),
        name='group_delete',
    ),
    path(
        'album/create/', views.AlbumCreateView.as_view(), name='album_create'
    ),
    path(
        'album/<int:pk>/', views.AlbumDetailView.as_view(), name='album_detail'
    ),
    path(
        'album/<int:pk>/edit/',
        views.AlbumUpdateView.as_view(),
        name='album_edit',
    ),
    path(
        'album/<int:pk>/delete/',
        views.AlbumDeleteView.as_view(),
        name='album_delete',
    ),
]

musican/musican/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('music.urls')),
]

musican/music/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.utils import timezone


class CommonInfo(models.Model):
    """Абстрактная базовая модель для общих полей."""

    name = models.CharField('Имя', max_length=100)
    country = models.CharField('Страна', max_length=100)

    class Meta:
        abstract = True


class Artist(CommonInfo):
    """Модель для артиста."""

    birth_day = models.DateField('Дата рождения')
    groups = models.ManyToManyField(
        'Group',
        related_name='artist_groups',
        verbose_name='Группа',
        blank=True,
    )
    tracks = models.ManyToManyField(
        'Track', related_name='artist_tracks', verbose_name='Треки', blank=True
    )
    info = models.TextField('Об исполнителе', null=True, blank=True)

    class Meta:
        verbose_name = 'Артист'
        verbose_name_plural = 'Артисты'
        ordering = ('name',)

    def __str__(self):
        return self.name

    def clean(self):
        super().clean()
        if self.birth_day > timezone.now().date():
            raise ValidationError('Дата рождения не может быть в будущем.')

    def get_group_artists(self):
        return ', '.join([group.name for group in self.groups.all()])

    get_group_artists.short_description = 'Группы'


class Group(CommonInfo):
    """Модель для группы."""

    date_foundation = models.DateField('Дата основания')
    members = models.ManyToManyField(
        Artist,
        related_name='group_members',
        verbose_name='Артисты',
        blank=True,
    )
    tracks = models.ManyToManyField(
        'Track', related_name='group_tracks', verbose_name='Треки', blank=True
    )

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'
        ordering = ('name',)

    def __str__(self):
        return self.name

    def clean(self):
        super().clean()
        if self.date_foundation > timezone.now().date():
            raise ValidationError('Дата основания не может быть в будущем.')


class Album(models.Model):
    """Модель для альбома."""

    name = models.CharField('Название альбома', max_length=100)
    release_year = models.DateField('Дата выхода')
    label = models.TextField('Описание')

    class Meta:
        verbose_name = 'Альбом'
        verbose_name_plural = 'Альбомы'
        ordering = ('release_year', 'name')

    def __str__(self):
        return self.name


class Track(models.Model):
    """Модель для трека."""

    name = models.CharField('Название трека', max_length=100)
    duration = models.FloatField(
        'Длительность', validators=[MinValueValidator(0.0)]
    )
    album = models.ForeignKey(
        Album,
        verbose_name='Альбом',
        related_name='track_album',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    artist = models.ForeignKey(
        Artist,
        verbose_name='Исполнитель',
        related_name='track_artist',
        on_delete=models.CASCADE,
    )
    group = models.ForeignKey(
        Group,
        verbose_name='Группа',
        related_name='track_group',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    genre = models.ForeignKey(
        'Genre',
        verbose_name='Жанр',
        on_delete=models.CASCADE,
    )
    text = models.TextField('Текст песни', blank=True, null=True)

    class Meta:
        verbose_name = 'Трек'
        verbose_name_plural = 'Треки'
        ordering = ('name',)
        constraints = (
            models.UniqueConstraint(
                fields=('group', 'name'), name='unique_group_name'
            ),
        )

    def __str__(self):
        return self.name

    def clean(self):
        super().clean()
        if self.duration <= 0:
            raise ValidationError(
                'Длительность трека должна быть положительной  или больше нуля.'
            )


class Genre(models.Model):
    """Модель для жанров."""

    name = models.CharField('Жанр', max_length=100, unique=True)

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'
        ordering = ('name',)

    def __str__(self):
        return self.name

musican/music/forms.py
from django import forms

from .models import Album, Artist, Genre, Group, Track


class ArtistForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = (
            'name',
            'country',
            'birth_day',
            'groups',
            'tracks',
            'info',
        )
        widgets = {
            'birth_day': forms.DateInput(attrs={'type': 'date'}),
            'info': forms.Textarea(attrs={'rows': 10, 'cols': 50}),
        }


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('name', 'country', 'date_foundation', 'members', 'tracks')
        widgets = {
            'date_foundation': forms.DateInput(attrs={'type': 'date'}),
        }


class TrackForm(forms.ModelForm):
    class Meta:
        model = Track
        fields = (
            'name',
            'duration',
            'album',
            'artist',
            'group',
            'genre',
            'text',
        )
        widgets = {
            'duration': forms.NumberInput(attrs={'step': 'any'}),
            'text': forms.Textarea(attrs={'rows': 4, 'cols': 40}),
        }


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ('name', 'release_year', 'label')
        widgets = {
            'release_year': forms.DateInput(attrs={'type': 'date'}),
            'label': forms.Textarea(attrs={'rows': 4, 'cols': 40}),
        }


class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ('name',)

musican/music/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from .forms import AlbumForm, ArtistForm, GenreForm, GroupForm, TrackForm
from .models import Album, Artist, Genre, Group, Track


class ArtistListView(ListView):
    model = Artist
    template_name = 'music/artist_list.html'
    context_object_name = 'artists'


class ArtistDetailView(DetailView):
    model = Artist
    template_name = 'music/artist_detail.html'
    context_object_name = 'artist'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tracks'] = self.object.track_artist.all()
        context['groups'] = self.object.groups.all()
        return context


class ArtistCreateView(CreateView):
    model = Artist
    form_class = ArtistForm
    template_name = 'music/form.html'
    success_url = reverse_lazy('music:artist_list')


class ArtistUpdateView(UpdateView):
    model = Artist
    form_class = ArtistForm
    template_name = 'music/form.html'
    success_url = reverse_lazy('music:artist_list')


class ArtistDeleteView(DeleteView):
    model = Artist
    template_name = 'music/confirm_delete.html'
    success_url = reverse_lazy('music:track_list')


class TrackListView(ListView):
    model = Track
    template_name = 'music/index.html'
    context_object_name = 'tracks'


class TrackDetailView(DetailView):
    model = Track
    template_name = 'music/track_detail.html'
    context_object_name = 'track'


class AlbumDetailView(DetailView):
    model = Album
    template_name = 'music/album_detail.html'
    context_object_name = 'album'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tracks'] = self.object.track_album.all()

        return context


class GroupListView(ListView):
    model = Group
    template_name = 'music/group_list.html'
    context_object_name = 'groups'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class GroupDetailView(DetailView):
    model = Group
    template_name = 'music/group_detail.html'
    context_object_name = 'group'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['members'] = self.object.artist_groups.all()
        context['tracks'] = self.object.track_group.all()
        return context


class GroupCreateView(CreateView):
    model = Group
    form_class = GroupForm
    template_name = 'music/form.html'
    success_url = reverse_lazy('music:group_list')


class GroupUpdateView(UpdateView):
    model = Group
    form_class = GroupForm
    template_name = 'music/form.html'
    success_url = reverse_lazy('music:group_list')


class GroupDeleteView(DeleteView):
    model = Group
    template_name = 'music/confirm_delete.html'
    success_url = reverse_lazy('music:group_list')


class TrackCreateView(CreateView):
    model = Track
    form_class = TrackForm
    template_name = 'music/form.html'
    success_url = reverse_lazy('music:track_list')


class TrackUpdateView(UpdateView):
    model = Track
    form_class = TrackForm
    template_name = 'music/form.html'
    success_url = reverse_lazy('music:track_list')


class TrackDeleteView(DeleteView):
    model = Track
    template_name = 'music/confirm_delete.html'
    success_url = reverse_lazy('music:track_list')


class AlbumCreateView(CreateView):
    model = Album
    form_class = AlbumForm
    template_name = 'music/form.html'
    success_url = reverse_lazy('music:track_list')


class AlbumUpdateView(UpdateView):
    model = Album
    form_class = AlbumForm
    template_name = 'music/form.html'
    success_url = reverse_lazy('music:track_list')


class AlbumDeleteView(DeleteView):
    model = Album
    template_name = 'music/confirm_delete.html'
    success_url = reverse_lazy('music:track_list')


class GenreCreateView(CreateView):
    model = Genre
    form_class = GenreForm
    template_name = 'music/form.html'
    success_url = reverse_lazy('music:genre_list')


class GenreUpdateView(UpdateView):
    model = Genre
    form_class = GenreForm
    template_name = 'music/form.html'
    success_url = reverse_lazy('music:genre_list')

musican/templates/music/album_detail.html
{% extends "base.html" %}

{% block title %}{{ album.name }}{% endblock %}

{% block main %}
  <div class="container">
    <section class="album__info">

      {% include "music/includes/links.html" with var=album %}

      <h1>Название альбома: {{ album.name }}</h1>
      <p>Год выпуска: {{ album.release_year }}</p>
      <p>Описание: {{ album.label }}</p>
  
      <div>
        <h2>Список песен в альбоме</h2>
        {% include "music/includes/tracks.html" %}
      </div>
    </section>
  </div>
{% endblock %}

musican/templates/music/artist_detail.html
{% extends "base.html" %}

{% block title %}{{ artist.name }}{% endblock %}

{% block main %}
  <div class="container">
    <section class="artist__info">
      {% include "music/includes/links.html" with var=artist %}

      <h1 class="artist__name">Исполнитель: {{ artist.name }}</h1>
      <p class="artist__birth-day">Дата рождения: {{ artist.birth_day }}</p>
      <p class="artist__country">Страна: {{ artist.country }}</p>

      <div class="artist__group">
        <p>Группы автора:</p>
        {% include "music/includes/groups.html" %}
      </div>

      <div>
        <h2>Песни исполнителя</h2>
        {% include "music/includes/tracks.html" %}
      </div>

      <p class="artist__description">{{ artist.info }}</p>
    </section>
  </div>
{% endblock %}

musican/templates/music/artist_list.html
{% extends "base.html" %}

{% block title %}Список исполнителей{% endblock %}

{% block main %}
  <div class="container">
    <section class="artist__list">
      <h1 class="title">Список исполнителей</h1>

      {% include "music/includes/artists.html" with var=artists %}
    </section>
  </div>
{% endblock %}

musican/templates/music/confirm_delete.html
{% extends "base.html" %}

{% block title %}Удалить {{ object.name }}{% endblock %}

{% block main %}
  <div class="container">
    <section class="form__box">
      <h1 class="form__title">Удалить: {{ object.name }}?</h1>
      <form class="form" method="post">
        {% csrf_token %}
        <button class="form__btn" type="submit">Удалить</button>
        <a href="{% url 'music:artist_list' %}">Отмена</a>
      </form>
    </section>
  </div>
{% endblock %}

musican/templates/music/form.html
{% extends "base.html" %}

{% block title %}
  {% if form.instance.pk %}Редактировать{% else %}Создать{% endif %} запись
{% endblock %}

{% block main %}
  <div class="container">
    <section class="form__box">
      <h1 class="form__title">
        {% if form.instance.pk %}Редактировать{% else %}Создать{% endif %} запись
      </h1>
      <form class="form" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="form__btn" type="submit">Сохранить</button>
      </form>
    </section>
  </div>
{% endblock %}

musican/templates/music/group_detail.html
{% extends "base.html" %}

{% block title %}{{ group.name }}{% endblock %}

{% block main %}
  <div class="container">
    <section class="group__info">

      {% include "music/includes/links.html" with var=group %}

      <h1>{{ group.name }}</h1>
      <p>Дата основания: {{ group.date_foundation }}</p>
    
      <div>
        <h2>Состав группы:</h2>
        {% include "music/includes/artists.html" with var=members %}
      </div>
    
      <div>
        <h2>Треки группы:</h2>
        {% include "music/includes/tracks.html" %}
      </div>
    </section>
  </div>
{% endblock %}

musican/templates/music/group_list.html
{% extends "base.html" %}

{% block main %}
  <div class="container">
   <section class="group__list"> 
    <h1 class="title">Список групп</h1>

    {% include "music/includes/groups.html" %}
   </section> 
  </div>
{% endblock %}

musican/templates/music/index.html
{% extends "base.html" %}

{% block title %}Список треков{% endblock %}

{% block main %}
  <div class="container">
    <h1 class="title">Список треков</h1>
    <section class="track__info">
      <ul class="track__list">
        {% for track in tracks %}
          <li class="track__item">
            <h2 class="track__name">
              <a href="{% url 'music:track_detail' track.id %}">{{ track.name }}</a>
            </h2>
            {% if track.group %}
              <a class="track__group" href="{% url 'music:group_detail' track.group.id %}">{{ track.group }}</a>
            {% endif %}
          </li>
        {% empty %}
          <li>Треков нет</li>
        {% endfor %}
      </ul>
    </section>
  </div>
{% endblock %}
    

musican/templates/music/track_detail.html
{% extends "base.html" %}

{% block title %}{{ track.name }}{% endblock %}

{% block main %}
  <div class="container">

    {% include "music/includes/links.html" with var=track %}

    <section class="track__info">
      <h1 class="track__title">{{ track.name }}</h1>
      <p class="artist__name">
        Артист: 
        <a href="{% url 'music:artist_detail' track.artist.pk %}">{{ track.artist }}</a>
      </p>
      <p class="album__name">
        Альбом: 
        <a href="{% url 'music:album_detail' track.album.pk %}">{{ track.album }}</a>
      </p>
      <p class="group__name">
        Группа:
        <a href="{% url 'music:group_detail' track.group.id %}">{{ track.group }}</a>
      </p>
      <p class="track__duration">Длительность: {{ track.duration }} мин.</p>
      <span class="track__genre">Жанр: {{ track.genre }}</span>
    </section>
    <div>
      <h2 class="track__text">Текст песни</h2>
      <pre>{{ track.text }}</pre>
    </div>
  </div>
{% endblock %}