musican/music/urls.py
from django.urls import path

from . import views

app_name = 'music'

urlpatterns = [
    path('tracks/', views.TrackListView.as_view(), name='track_list'),
    path(
        'tracks/<int:pk>/',
        views.TrackDetailView.as_view(),
        name='track_detail',
    ),
    path(
        'track/create/', views.TrackCreateView.as_view(), name='track_create'
    ),
    path(
        'track/<int:pk>/edit/',
        views.TrackUpdateView.as_view(),
        name='track_edit',
    ),
    path(
        'track/<int:pk>/delete/',
        views.TrackDeleteView.as_view(),
        name='track_delete',
    ),
    path('artists/', views.ArtistListView.as_view(), name='artist_list'),
    path(
        'artist/<int:pk>/',
        views.ArtistDetailView.as_view(),
        name='artist_detail',
    ),
    path(
        'artist/create/',
        views.ArtistCreateView.as_view(),
        name='artist_create',
    ),
    path(
        'artist/<int:pk>/edit/',
        views.ArtistUpdateView.as_view(),
        name='artist_edit',
    ),
    path(
        'artist/<int:pk>/delete/',
        views.ArtistDeleteView.as_view(),
        name='artist_delete',
    ),
    path('groups/', views.GroupListView.as_view(), name='group_list'),
    path(
        'group/<int:pk>/', views.GroupDetailView.as_view(), name='group_detail'
    ),
    path(
        'group/create/', views.GroupCreateView.as_view(), name='group_create'
    ),
    path(
        'group/<int:pk>/edit/',
        views.GroupUpdateView.as_view(),
        name='group_edit',
    ),
    path(
        'group/<int:pk>/delete/',
        views.GroupDeleteView.as_view(),
        name='group_delete',
    ),
    path(
        'album/create/', views.AlbumCreateView.as_view(), name='album_create'
    ),
    path(
        'album/<int:pk>/', views.AlbumDetailView.as_view(), name='album_detail'
    ),
    path(
        'album/<int:pk>/edit/',
        views.AlbumUpdateView.as_view(),
        name='album_edit',
    ),
    path(
        'album/<int:pk>/delete/',
        views.AlbumDeleteView.as_view(),
        name='album_delete',
    ),
]

musican/musican/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('music.urls')),
]

musican/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout',
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login',
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change',
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done',
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset',
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url='/auth/reset/done/',
        ),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
]

musican/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'first_name',
            'username',
        )

musican/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('music:track_list')
    template_name = 'users/signup.html'

musican/templates/users/logged_out.html
{% extends 'base.html' %}

{% block title %}Вы вышли из системы{% endblock %}
{% block main %}
  <div class="container">
    <section>
      <p>Вы успешно вышли из системы.</p>
    </section>
  </div>
{% endblock %} 

musican/templates/users/login.html
{% extends "base.html" %}

{% block title %}Войти{% endblock %}

{% block main %}
  <div class="container">
    <section>
      <h2>Вход</h2>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Войти</button>
      </form>

      <a href="{% url 'users:password_reset' %}">Сбросить пароль</a>
    </section>
  </div>
{% endblock %}

musican/templates/users/password_change_done.html
{% extends "base.html" %}

{% block title %}Пароль изменен{% endblock %}

{% block main %}
  <div class="container">
    <h2>Пароль успешно изменен</h2>
    <p>Ваш пароль был успешно изменен.</p>
    <a href="{% url 'login' %}">Войти снова</a>
  </div>
{% endblock %}

musican/templates/users/password_change_form.html
{% extends "base.html" %}

{% block title %}Смена пароля{% endblock %}

{% block main %}
  <div class="container">
    <h2>Смена пароля</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Сменить пароль</button>
    </form>
  </div>
{% endblock %}

musican/templates/users/password_reset_complete.html
{% extends "base.html" %}

{% block title %}Восстановление пароля{% endblock %}

{% block main %}
  <div class="container">
    <h2>Пароль успешно изменен</h2>
    <p>Ваш пароль был успешно изменен. Теперь вы можете войти с новым паролем.</p>
    <a href="{% url 'login' %}">Войти</a>
  </div>
{% endblock %}

musican/templates/users/password_reset_confirm.html
{% extends "base.html" %}

{% block title %}Восстановление пароля{% endblock %}

{% block main %}
  <div class="container">  
    <h2>Установка нового пароля</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сменить пароль</button>
    </form>
  </div>
{% endblock %}

musican/templates/users/password_reset_done.html
{% extends "base.html" %}

{% block title %}Восстановление пароля{% endblock %}

{% block main %}
  <div class="container">
    <h2>Письмо отправлено</h2>
    <p>Инструкция по восстановлению пароля была отправлена на указанный email.</p>
  </div>
{% endblock %}

musican/templates/users/password_reset_form.html
{% extends "base.html" %}

{% block title %}Восстановление пароля{% endblock %}

{% block main %}
  <div class="container">
    <h2>Восстановление пароля</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить запрос на восстановление пароля</button>
    </form>
  </div>
{% endblock %}

musican/templates/users/signup.html
{% extends 'base.html' %}

{% block main %}
  <div class="container">
    <section>
      <h2>Регистрация</h2>
      <form method="post">
        {% csrf_token %}

        <!-- Отображение формы -->
        {{ form.non_field_errors }}
        {% for field in form %}
          <div>
            {{ field.label_tag }} <!-- Отображение метки -->
            {{ field }}  <!-- Поле формы -->
            {% if field.errors %}
              <div class="error">
                {% for error in field.errors %}
                  <p>{{ error }}</p>
                {% endfor %}
              </div>
            {% endif %}
          </div>
        {% endfor %}

        <button type="submit">Зарегистрироваться</button>
      </form>
    </section>
  </div>
{% endblock %}