musican/music/urls.py
from django.urls import path

from . import views

app_name = 'music'

urlpatterns = [
    path('tracks/', views.TrackListView.as_view(), name='track_list'),
    path(
        'tracks/<int:pk>/',
        views.TrackDetailView.as_view(),
        name='track_detail',
    ),
    path(
        'track/create/', views.TrackCreateView.as_view(), name='track_create'
    ),
    path(
        'track/<int:pk>/edit/',
        views.TrackUpdateView.as_view(),
        name='track_edit',
    ),
    path(
        'track/<int:pk>/delete/',
        views.TrackDeleteView.as_view(),
        name='track_delete',
    ),
    path('artists/', views.ArtistListView.as_view(), name='artist_list'),
    path(
        'artist/<int:pk>/',
        views.ArtistDetailView.as_view(),
        name='artist_detail',
    ),
    path(
        'artist/create/',
        views.ArtistCreateView.as_view(),
        name='artist_create',
    ),
    path(
        'artist/<int:pk>/edit/',
        views.ArtistUpdateView.as_view(),
        name='artist_edit',
    ),
    path(
        'artist/<int:pk>/delete/',
        views.ArtistDeleteView.as_view(),
        name='artist_delete',
    ),
    path('groups/', views.GroupListView.as_view(), name='group_list'),
    path(
        'group/<int:pk>/', views.GroupDetailView.as_view(), name='group_detail'
    ),
    path(
        'group/create/', views.GroupCreateView.as_view(), name='group_create'
    ),
    path(
        'group/<int:pk>/edit/',
        views.GroupUpdateView.as_view(),
        name='group_edit',
    ),
    path(
        'group/<int:pk>/delete/',
        views.GroupDeleteView.as_view(),
        name='group_delete',
    ),
    path(
        'album/create/', views.AlbumCreateView.as_view(), name='album_create'
    ),
    path(
        'album/<int:pk>/', views.AlbumDetailView.as_view(), name='album_detail'
    ),
    path(
        'album/<int:pk>/edit/',
        views.AlbumUpdateView.as_view(),
        name='album_edit',
    ),
    path(
        'album/<int:pk>/delete/',
        views.AlbumDeleteView.as_view(),
        name='album_delete',
    ),
]

musican/musican/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('music.urls')),
]

musican/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout',
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login',
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change',
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done',
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset',
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url='/auth/reset/done/',
        ),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
]

musican/templates/includes/footer.html
<footer class="footer">
  <div class="container">
      <p class="footer__text">© {% now 'Y' %} Моя музыка. Все права защищены.</p>
      <nav class="footer__nav">
          <ul class="footer__list">
              <li class="footer__item">
                  <a href="#" class="footer__link">Контакты</a>
              </li>
              <li class="footer__item">
                  <a href="#" class="footer__link">О сайте</a>
              </li>
          </ul>
      </nav>
  </div>
</footer>

musican/templates/includes/header.html
<header class="header">
  <div class="container">
    <div class="header__inner">
      <nav class="nav nav__music">
        <ul class="nav__list">
          <li class="nav__item">
            <a href="{% url 'music:track_list' %}" class="nav__link">Главная</a>
          </li>
          <li class="nav__item">
            <a href="{% url 'music:artist_list' %}" class="nav__link">Список исполнителей</a>
          </li>
          <li class="nav__item">
            <a href="{% url 'music:group_list' %}" class="nav__link">Список групп</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav__item">
              <a href="{% url 'music:artist_create' %}" class="nav__link">Создать исполнителя</a>
            </li>
            <li class="nav__item">
              <a href="{% url 'music:track_create' %}" class="nav__link">Создать трек</a>
            </li>
            <li class="nav__item">
              <a href="{% url 'music:group_create' %}" class="nav__link">Создать группу</a>
            </li>
            <li class="nav__item">
              <a href="{% url 'music:album_create' %}" class="nav__link">Создать альбом</a>
            </li>
          {% endif %}
        </ul>
      </nav>
      <nav class="nav nav__user">
        <ul class="nav__list">
            {% if user.is_authenticated %}
            <li class="nav__item nav__username">
                <a href="#" class="nav__link user-dropdown-toggle">Пользователь: {{ user.username }}</a>
                <ul class="user-dropdown">
                    <li class="nav__item">
                        <a href="{% url 'users:password_change' %}" class="nav__link">Изменить пароль</a>
                    </li>
                    <li class="nav__item">
                        <form action="{% url 'users:logout' %}" method="post" class="logout-form">
                            {% csrf_token %}
                            <button type="submit" class="btn btn--logout">Выйти</button>
                        </form>
                    </li>
                </ul>
            </li>
            {% else %}
            <li class="nav__item"> 
                <a href="{% url 'users:login' %}" class="nav__link">Войти</a>
            </li>
            <li class="nav__item"> 
                <a href="{% url 'users:signup' %}" class="nav__link">Регистрация</a>
            </li>
            {% endif %}
        </ul>
    </nav>
        </div>
  </div>
</header>